---
    r1:
        hostname:'r1'
        groups:
            -'routers'
        ports:
            -'FastEthernet0/0'
             'Fa0/0' 
    r2:
        hostname:'r2'
        groups:
            -'routers'
        ports:
            -'FastEthernet0/0'
             'Fa0/0' 
    r3:
        hostname:'r3'
        groups:
            -'routers'
        ports:
            -'FastEthernet0/0'
             'Fa0/0' 

    sw1:
        hostname:'sw1'
        groups:
            -'switches'
        ports:
            -'GigabitEthernet0/0'
             'GigabitEthernet0/1'
             'GigabitEthernet0/2'
             'GigabitEthernet0/3'  
             'Gi0/0' 
             'Gi0/1' 
             'Gi0/2' 
             'Gi0/3' 

    sw2:
        hostname:'sw2'
        groups:
            -'switches'
        ports:
             'GigabitEthernet0/1'
             'GigabitEthernet0/2'
             'GigabitEthernet0/3'  
             'Gi0/1' 
             'Gi0/2' 
             'Gi0/3' 
    sw3:
        hostname:'sw3'
        groups:
            -'switches'
        ports:
            -'GigabitEthernet0/0'
             'GigabitEthernet0/1'
             'GigabitEthernet0/2'
             'GigabitEthernet0/3'  
             'Gi0/0' 
             'Gi0/1' 
             'Gi0/2' 
             'Gi0/3' 
    sw4:
        hostname:'sw4'
        groups:
            -'switches'
        ports:
            -'GigabitEthernet0/0'
             'GigabitEthernet0/1'
             'GigabitEthernet0/2'
             'GigabitEthernet0/3'  
             'Gi0/0' 
             'Gi0/1' 
             'Gi0/2' 
             'Gi0/3' 
